# Generated by Django 2.0.7 on 2018-07-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoe',
            new_name='Data',
        ),
    ]
